name: Changesets Check
on:
  pull_request:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  check:
    name: Changesets Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Enable Corepack
        id: enable-corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - name: Check for Changesets
        run: pnpm changeset status --since=origin/main

  preview:
    needs: check
    name: Changesets Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Enable Corepack
        id: enable-corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Preview Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}"
          npm_config_registry=https://npm.pkg.github.com pnpm changeset version --snapshot preview-${{ github.event.pull_request.head.sha }}
          npm_config_registry=https://npm.pkg.github.com pnpm changeset publish --no-git-tag --tag preview-${{ github.event.pull_request.head.sha }}
