name: Changesets Check
on:
  pull_request:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  check:
    name: Changesets Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Enable Corepack
        id: enable-corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - name: Check for Changesets
        run: pnpm changeset status --since=origin/main

  preview:
    needs: check
    name: Changesets Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Enable Corepack
        id: enable-corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      # - name: Generate Preview Version
      #   id: preview-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     pnpm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}"
      #     npm_config_registry=https://npm.pkg.github.com pnpm changeset version --snapshot preview-${{ steps.short-sha.outputs.sha }}
      #     npm_config_registry=https://npm.pkg.github.com pnpm changeset publish --no-git-tag --tag preview-${{ steps.short-sha.outputs.sha }}

      - name: Generate Preview Version
        id: preview-release
        uses: changesets/action@v1
        with:
          version: pnpm run version-snapshot -- preview-${{ steps.short-sha.outputs.sha }}
          publish: pnpm run publish-snapshot -- preview-${{ steps.short-sha.outputs.sha }}
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: buildingcash/json-to-markdown-table-action@v1
        if: steps.preview-release.outputs.published == true
        id: table
        with:
          json: ${{ steps.preview-release.outputs.publishedPackages }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        if: steps.preview-release.outputs.published == true
        with:
          message: |
            # Snapshot packages
            ${{ steps.table.outputs.table }}
