name: Publish Snapshot

on:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  snapshot:
    if: contains(github.event.pull_request.labels.*.name, 'snapshot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org

      - name: Enable Corepack
        id: enable-corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Check for Changesets
        id: check-changesets
        run: pnpm changeset status --since=origin/main

      - name: Calculate Preview Version
        id: preview-version
        run: |
          pnpm changeset version --snapshot preview-${{ steps.short-sha.outputs.sha }}
          git diff --name-only --diff-filter=u | grep package.json | xargs -n 1 jq '. as $root | {name: ("`"+$root.name+"`"), version: ("`"+$root.version+"`"), registry: ("[NPM](https://www.npmjs.com/package/"+$root.name+"/v/"+$root.version+")")}' | jq -s -c > changesets.json
          echo "publishedPackages=$(cat changesets.json)" >> $GITHUB_OUTPUT
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Snapshot Version
        id: preview-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm changeset publish --no-git-tag --tag preview-${{ steps.short-sha.outputs.sha }}

      - uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json: ${{ steps.preview-version.outputs.publishedPackages }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### 📦️ Snapshot packages
            Latest commit: ${{ github.sha }}
            ${{ steps.table.outputs.table }}
          comment_tag: execution
