name: Changesets Check
on:
  pull_request:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  check:
    name: Changesets Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Enable Corepack
        id: enable-corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - name: Check for Changesets
        run: pnpm changeset status --since=main
